### ISSUE TITLE
User tag vs. Rails 4.2

### ISSUE THREAD

**Issue by 2xG** [raulanatol/camaleon-user-tag-plugin#1]
AFAIK in 4.2 they've dropped attr_accessible. With this plugin installed my server won't start. My current knowledge do not permit me do fix it by myself without a damage to plugin functionality.

**Comment by raulanatol** [comment]
Hi @2xG!

I've changed the attr_accesible using strong parameters (http://edgeapi.rubyonrails.org/classes/ActionController/StrongParameters.html).
I've push a new version too.

Regards.

**Comment by 2xG** [comment]
As I see in your las commit it was quite easy to fix.
Thank you very much! Good luck!
